version: "3.7"
services:
  nginx:
    image: nginx:latest
    expose:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    
  backend:
    image: hungnln98/vleague-app:latest
    restart: always
    ports:
      - "8080:8080"
  frontend:
    image: hungnln98/vleague-web-app:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
  