# version: "3.7"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/nginx-selfsigned.key:/etc/nginx/ssl/certs/nginx-selfsigned.key
      - ./ssl/nginx-selfsigned.crt:/etc/nginx/ssl/private/nginx-selfsigned.crt
  backend:
    image: hungnln98/vleague-app:latest
    # image: local-be:v1

    restart: always
    # ports:
    #   - "8080:8080"
  frontend:
    image: hungnln98/vleague-web-app:latest

    restart: always
    depends_on:
      - backend
    
  